### PR TITLE
Fix for puppet4 (uses init provider that does not have enableable fea…

### PR DESCRIPTION
**Pull request by mcanevet**
…tures)

### CODE REVIEW

**Comment by raphink** [comment]
This is sadly ugly…

**Comment by ckaenzig** [comment]
The documentation says that the `systemd` provider is default for `redhat 7` (https://docs.puppetlabs.com/references/latest/type.html#service-provider-systemd). Is that wrong? It also says that provider supports `enableable` and `refreshable`.

**Comment by mcanevet** [comment]
@ckaenzig the problem is that puppet do a `systemctl list-unit-files --type service` to list services (https://github.com/puppetlabs/puppet/blob/master/lib/puppet/provider/service/systemd.rb#L19) and it looks like nagios init script is broken and thus fallbacks to `init` provider, which does not support enableable feature.

**Comment by ckaenzig** [comment]
@mcanevet Hmm, from what I see, the nagios packages from epel don't provide a systemd service configuration at all. That's a bit sad, indeed.

**Pull request closed without merging**
